from __future__ import annotations

from typing import Any


DISCLAIMER = (
    "This report was generated by an AI contract analysis system and does not "
    "constitute legal advice. All findings must be reviewed and validated by "
    "a qualified attorney before any contractual action is taken."
)


def generate_report_markdown(
    extraction: dict[str, Any],
    analysis: dict[str, Any],
    redlines: list[dict[str, Any]],
    audience: str,
) -> str:
    metadata = extraction["contract_metadata"]
    analysis_items = analysis["analysis"]

    critical = [item for item in analysis_items if item["negotiation_priority"] == "MUST CHANGE" or item["legal_risk"] == "CRITICAL"]
    high = [item for item in analysis_items if item["negotiation_priority"] == "SHOULD CHANGE" or item["legal_risk"] == "HIGH"]
    acceptable = [item for item in analysis_items if item["negotiation_priority"] == "ACCEPT"]

    recommendation = _recommendation(analysis["overall_contract_risk"])

    lines: list[str] = []
    lines.append("# Contract Review Report")
    lines.append("")
    lines.append("## Section 1 - Contract Snapshot")
    lines.append(f"- Contract type: {metadata['contract_type']}")
    lines.append(f"- Parties: {metadata['parties'][0]} and {metadata['parties'][1]}")
    lines.append(f"- Effective date: {metadata['effective_date']}")
    lines.append(f"- Governing law: {metadata['governing_law']}")
    lines.append(f"- Total clauses reviewed: {metadata['total_clauses_found']}")
    lines.append(f"- Overall risk rating: {analysis['overall_contract_risk']} ({analysis['overall_risk_summary']})")
    lines.append(f"- Recommendation: {recommendation}")
    lines.append("")

    lines.append("## Section 2 - Critical Issues (Must Change)")
    if critical:
        for item in critical:
            lines.append(f"- {item['clause_id']} {item['clause_type']}: {item['deviation_summary']}")
            lines.append(f"  Consequence: {item['real_world_impact']}")
            lines.append("  Recommended fix: Align with playbook language and apply proposed redline.")
    else:
        lines.append("- None identified.")
    lines.append("")

    lines.append("## Section 3 - High Priority Issues (Should Change)")
    if high:
        for item in high:
            lines.append(f"- {item['clause_id']} {item['clause_type']}: {item['deviation_summary']}")
            lines.append(f"  Consequence: {item['real_world_impact']}")
            lines.append("  Recommended fix: Negotiate reciprocal language and narrower obligation scope.")
    else:
        lines.append("- None identified.")
    lines.append("")

    lines.append("## Section 4 - Missing Clauses")
    missing = metadata["missing_standard_clauses"]
    if missing:
        for clause_name in missing:
            lines.append(f"- {clause_name}: Add to reduce legal and operational ambiguity. Urgency: HIGH")
    else:
        lines.append("- No standard clause gaps detected.")
    lines.append("")

    lines.append("## Section 5 - Acceptable Clauses")
    if acceptable:
        for item in acceptable:
            lines.append(f"- {item['clause_id']} {item['clause_type']}")
    else:
        lines.append("- None currently in ACCEPT state.")
    lines.append("")

    lines.append("## Section 6 - Negotiation Strategy")
    top3 = critical[:3] if critical else high[:3]
    if top3:
        lines.append("- Top 3 lead issues:")
        for item in top3:
            lines.append(f"  - {item['clause_id']} {item['clause_type']}")
    else:
        lines.append("- Top 3 lead issues: none.")
    lines.append("- Suggested concessions: phased implementation timeline, mutual wording refinements, notice period flexibility.")
    lines.append("- Never concede: uncapped one-sided liability, unilateral indemnification, missing data protection framework.")
    lines.append(f"- Estimated negotiation complexity: {_complexity(analysis['overall_contract_risk'], len(redlines))}")
    lines.append("")

    lines.append("## Section 7 - Recommended Next Steps")
    lines.append("1. Legal (Urgent): Resolve MUST CHANGE clauses and confirm jurisdiction-specific enforceability.")
    lines.append("2. Business (High): Validate commercial impact of liability and termination terms.")
    lines.append("3. Procurement (Medium): Incorporate fallback language for counterparty negotiations.")
    lines.append("")

    lines.append("## Section 8 - Legal Disclaimer")
    lines.append(DISCLAIMER)
    lines.append("")
    lines.append("This output requires review by a qualified attorney before execution.")
    lines.append(f"Audience profile applied: {audience}")

    return "\n".join(lines)


def _recommendation(overall_risk: str) -> str:
    if overall_risk == "CRITICAL":
        return "REJECT"
    if overall_risk == "HIGH":
        return "APPROVE WITH CHANGES"
    return "APPROVE WITH CHANGES"


def _complexity(overall_risk: str, redline_count: int) -> str:
    if overall_risk == "CRITICAL" or redline_count >= 5:
        return "HIGH"
    if overall_risk == "HIGH" or redline_count >= 3:
        return "MEDIUM"
    return "LOW"
