from __future__ import annotations

from typing import Callable, TypeVar

from pydantic import BaseModel, ValidationError

from integrations.json_utils import parse_llm_json


SchemaT = TypeVar("SchemaT", bound=BaseModel)


class LLMValidationError(RuntimeError):
    pass


REQUIRED_REPORT_HEADERS = [
    "SECTION 1",
    "SECTION 2",
    "SECTION 3",
    "SECTION 4",
    "SECTION 5",
    "SECTION 6",
    "SECTION 7",
    "SECTION 8",
]

REQUIRED_REPORT_DISCLAIMER = (
    "This report was generated by an AI contract analysis system and does not "
    "constitute legal advice. All findings must be reviewed and validated by "
    "a qualified attorney before any contractual action is taken."
)

REQUIRED_REVIEW_CLOSING = "This output requires review by a qualified attorney before execution."


def parse_and_validate(raw: str, schema: type[SchemaT]) -> SchemaT:
    try:
        parsed = parse_llm_json(raw)
        return schema.model_validate(parsed)
    except (ValueError, ValidationError) as exc:
        raise LLMValidationError(str(exc)) from exc


def run_json_step_with_retries(call: Callable[[], str], schema: type[SchemaT], attempts: int = 2) -> SchemaT:
    last_error: Exception | None = None
    for _ in range(attempts):
        try:
            return parse_and_validate(call(), schema)
        except Exception as exc:
            last_error = exc
    raise LLMValidationError(f"Failed to validate LLM output after {attempts} attempts: {last_error}")


def validate_report_text(report_text: str) -> str:
    missing = [header for header in REQUIRED_REPORT_HEADERS if header not in report_text]
    if missing:
        raise LLMValidationError(f"Report missing required sections: {', '.join(missing)}")
    if REQUIRED_REPORT_DISCLAIMER not in report_text:
        raise LLMValidationError("Report missing required legal disclaimer.")
    if REQUIRED_REVIEW_CLOSING not in report_text:
        raise LLMValidationError("Report missing required attorney review closing.")
    return report_text
